[project]
name = "capy-chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.0",
    "httpx>=0.27.2",
    "pytest>=8.3.3",
    "sqlalchemy>=2.0.35",
    "websockets>=13.1",
]
